### PR TITLE
Port protocol to protobuf

### PR DESCRIPTION
**Pull request by sindrehan**
Remaining for feature parity with current protocol:
- [x] More documentation. The SetMotionInput rpc has an example of how docstrings are used in Protobuf files.
- [x] Port the messages sent over UDP -- Currently only the RPCs are ported.

Further actions:
- [x] Go through #3 and add the requested messages.
- [x] ~Figure out how we should handle more direct control of the drone, eg. to solve the issue in https://github.com/BluEye-Robotics/blueye.sdk/issues/85~ Will require on-board SDK. 
- [x] Add Github Action for generating package for C#
- [x] Add Github Action for generating package for Python
- [x] Add Github Action for generating package for c++

### CODE REVIEW

**Comment by follesoe** [comment]
There is an issue with the protobuf Visual Studio language extension, where it will complain that the `common.proto` file is not found. This issue occurs if you open the repository root directory, which I guess is most common, and not the protobuf directory itself.

The issue is described here: https://github.com/zxh0/vscode-proto3/issues/12

The workaround is to add a `.vscode/settings.json` file and specify the `proto_path` argument:

```json
{
    "protoc": {
        "options": [
            "--proto_path=${workspaceRoot}/protobuf_definitions"
        ]
    }
}
```

I have done this (but `.vscode` folder is normally ignored as it may contain user-specific settings as well).

**Comment by follesoe** [comment]
For documentation, I suggest we use `protoc-gen-doc` tool: https://github.com/pseudomuto/protoc-gen-doc. I have added a shell script called `protoc-gen-doc` that invokes the tool and outputs Markdown and HTML documentation in a `docs` directory (which is added to `.gitignore`).

Later we can use commit the Markdown file to the `ProtocolDefinitions` repository Wiki.

**Comment by follesoe** [comment]
Have added a `protolint.sh` script to run the `protolint` Docker container on the project. See https://github.com/yoheimuta/protolint for details, and https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml for the example configuration file.

By default, it follows the official style guide from https://developers.google.com/protocol-buffers/docs/style.

**Comment by erlenner** [comment]
@follesoe Note the new iso gain field for the new cameras: ee355faa515a5b9a9738d4de8c9512fdf2e78764

**Comment by erlenner** [comment]
@follesoe See new thickness fields in OverlayParameters: https://github.com/BluEye-Robotics/ProtocolDefinitions/pull/14/commits/5d0e4ba715a6cf68a9421b7d34e902ba0528ffd7

For v2, we just set the thickness unit depending on the depth unit.

**Comment by follesoe** [comment]
We have three ways to specify if a message is valid:

- `is_valid` is used by `PositionEstimate`
- `valid` is used by `Altitude` and `ForwardDistance`
- `valid_measurement` is used by `ThicknessGauge`

Should standardise on one 😅

**Review by follesoe — APPROVED** [review]

**Pull request merged**
