### PR TITLE
add video overlay commands

### PR DESCRIPTION
**Pull request by erlenner**
Depends on https://github.com/BluEye-Robotics/p2_drone/pull/241

### CODE REVIEW

**Comment by follesoe** [comment]
Are overlays enabled in the current dev build? I can add it as a dev only setting under Camera settings in the app, so that we can start testing (I can also make the app setting so that it forces you to use 720p/25fps if enabling it).

**Comment by erlenner** [comment]
@follesoe The overlay logic in gst_rtsp_record has been in blunux dev since 1.6.243 (March 5th). However, the bindings between the app protocol and ros service calls are not merged yet: https://github.com/BluEye-Robotics/p2_drone/pull/241.

**Comment by erlenner** [comment]
But yes, it would be great if you added the setting so we can verify that it works before creating a new dev image.

**Comment by erlenner** [comment]
https://github.com/BluEye-Robotics/p2_drone/pull/241 is now merged, but I guess we don't merge this until we release the overlay feature, which won't be in 1.6.

**Comment by sindrehan** [comment]
@erlenner I assume this aligned with the version that was released today, and ready to be merged?

**Comment by erlenner** [comment]
@sindrehan Yes

**Comment by erlenner** [comment]
@sindrehan BTW, I used array syntax for these types: https://github.com/BluEye-Robotics/ProtocolDefinitions/pull/13/files#diff-68cea24f7926f9917716826632757ba5R608

Not sure how it plays with the autogenerated python code.

**Comment by sindrehan** [comment]
Will have to extend the generator the support the array syntax, but that shouldn't be a problem.

**Pull request merged**
